name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create torrents
        uses: devopsx/action-release-torrent@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/index.js
            src/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            dist/index.js
            src/*
            torrents/*
